#!/usr/bin/env bash

usage() {
    echo 'Usage: dil'
    echo
    echo 'Displays the list of Docker images'
    echo
    echo 'Optional arguments:'
    echo '  -h, --help             Show this help message and exit'
}

if [[ $# -gt 0 ]]; then
    usage
    exit 1
fi

docker image list