#!/usr/bin/bash

# Environment setup
set -o pipefail
original_path="${PWD}" # If needed
cd "$(dirname "$0")" || exit

echo "----------------------------- update -----------------------------------"
sudo pacman -Sy
echo "----------------------------- pacman -----------------------------------"
sudo pacman -Ss "${1}"
echo "----------------------------- yay --------------------------------------"
yay -Ss "${1}"
