#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/bash_modules/terminal.sh"

log_title "[s]tatus"

[[ $# -gt 0 ]] && exit 1

log_message "❯ git status"
git status
log_line
log_message "❯ tk list"
tk list
log_line
log_message "❯ tk note"
tk note
