#!/usr/bin/env bash

# Environment setup
set -o pipefail
original_path="${PWD}" # If needed
cd "$(dirname "$0")" || exit

sudo echo "----------------------------- flatpak ----------------------------------"
flatpak upgrade --assumeyes
echo "----------------------------- brew -------------------------------------"
brew upgrade
echo "----------------------------- node -------------------------------------"
nvm install node
echo "----------------------------- deno -------------------------------------"
deno upgrade
echo "----------------------------- pacman -------------------------------------"
sudo pacman -Syu
echo "----------------------------- yay -------------------------------------"
yay -Syu
