#!/usr/bin/env bash

source "$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)/init.sh"

log_tf_title "[t]ofu [a]pply [plan-file]"

[[ "${#}" -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]] && exit 1

if [[ -n "${1}" ]]; then
  log_message "❯ tofu apply ${1}"
  tofu apply "${1}"
  exit 0
fi

log_message "❯ tofu apply"
tofu apply
