#!/usr/bin/env bash

usage() {
    cat <<EOF

Usage: td [-h]

OpenTofu Destroy

Runs a tofu destroy

Optional arguments:
  -h, --help             Show this help message and exit

EOF
}

if [[ "${#}" -gt 0 ]]; then
    usage
    exit 0
fi

tofu destroy
