#!/usr/bin/env bash

usage() {
    cat <<EOF

Usage: ti [-h]

OpenTofu Initialisation

Runs a tofu init with upgrade then a plan

Optional arguments:
  -h, --help             Show this help message and exit

EOF
}

if [[ "${#}" -gt 0 ]]; then
    usage
    exit 0
fi

tofu init -upgrade
tofu plan
