#!/usr/bin/env bash

source "$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)/init.sh"

log_tf_title "[t]ofu [i]nit [bucket-name]"

[[ $# -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]] && exit 1

log_message "Removing .terraform directory and .terraform.lock.hcl file"
log_message "❯ rm -rf .terraform && rm -f .terraform.lock.hcl"
rm -rf .terraform && rm -f .terraform.lock.hcl

if [[ -z "${1}" ]]; then
  log_message "❯ tofu init -upgrade"
  tofu init -upgrade
  exit 0
fi

log_message "Bucket Name: '${1}'"
log_message "❯ tofu init -upgrade -backend-config=\"bucket=${1}\""
tofu init -upgrade -backend-config="bucket=${1}"
