#!/usr/bin/env bash

source "$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)/init.sh"

log_tf_title "[t]ofu [i]nit & [p]lan"

[[ $# -gt 0 ]] && exit 1

log_message "Removing .terraform directory and .terraform.lock.hcl file"
log_message "❯ rm -rf .terraform && rm -f .terraform.lock.hcl"
rm -rf .terraform && rm -f .terraform.lock.hcl
log_message "❯ tofu init -upgrade"
tofu init -upgrade


log_fullline
PLAN_FILE="$(new_tf_plan_file)"

log_message "Saving plan to:"
log_message "'${PLAN_FILE}'"
log_message "❯ tofu plan -out='$(basename "${PLAN_FILE}")'"
tofu plan -out="${PLAN_FILE}"
