#!/usr/bin/env bash

usage() {
    cat <<EOF

Usage: tp [-h]

OpenTofu Plan

Runs a tofu plan

Optional arguments:
  -h, --help             Show this help message and exit

EOF
}

if [[ "${#}" -gt 0 ]]; then
    usage
    exit 0
fi

tofu plan
