#!/usr/bin/env bash

source "$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)/init.sh"

log_tf_title "[t]ofu [p]lan"

[[ $# -gt 0 ]] && exit 1

PLAN_FILE="$(new_tf_plan_file)"

log_message "Saving plan to:"
log_message "'${PLAN_FILE}'"
log_message "❯ tofu plan -out='$(basename "${PLAN_FILE}")'"
tofu plan -out="${PLAN_FILE}"
