#!/usr/bin/env bash

usage() {
    cat <<EOF

Usage: ts [-h]

OpenTofu Show

Runs a OpenTofu Show

Optional arguments:
  -h, --help             Show this help message and exit

EOF
}

if [[ "${#}" -gt 0 ]]; then
    usage
    exit 0
fi

tofu show
