#!/usr/bin/env bash

usage() {
    cat <<EOF

Usage: tsl [-h]

OpenTofu State List

Runs a OpenTofu State List

Optional arguments:
  -h, --help             Show this help message and exit

EOF
}

if [[ "${#}" -gt 0 ]]; then
    usage
    exit 0
fi

tofu state list
