#!/usr/bin/env bash

usage() {
    cat <<EOF

Usage: tsrm <resource-id> [-h]

OpenTofu State RM

Runs a OpenTofu State Remove

Required arguments:
  resource-id            Resource to remove

Optional arguments:
  -h, --help             Show this help message and exit

EOF
}

if [[ "${#}" -ne 1 ]] || [[ "${1}" == "-h" ]] || [[ "${1}" == "--help" ]]; then
    usage
    exit 0
fi

tofu state rm "${1}"
