#!/usr/bin/env bash

source "$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)/init.sh"

log_tf_title "[t]ofu [s]tate [r]e[m]ove <resource-id>"

[[ "${#}" -ne 1 || "${1}" == "-h" || "${1}" == "--help" ]] && exit 1

log_message "❯ tofu state rm ${1}"
tofu state rm "${1}"
