#!/usr/bin/env bash

source "$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)/init.sh"

log_tf_title "[t]ofu [w]atch"
log_message "This command will run 'tofu fmt -recursive' and 'tofu validate'"
log_message "on every file change in the current directory."

[[ $# -gt 0 ]] && exit 1

log_message "❯ rg -l '.' | entr -c bash -c \"echo \\\"-- \$(date +%T) --\\\" && tofu fmt -recursive && tofu validate\""
log_pressanykey

rg -l '.' | entr -c bash -c "echo \"-- \$(date +%T) --\" && tofu fmt -recursive && tofu validate"
