#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "[g]it [a]dd [file-path]"

[[ "${#}" -ne 1 || "${1}" == "-h" || "${1}" == "--help" ]] && exit 1

log_message "❯ git add ${1}"
git add "${1}"
log_message "❯ git status ${1}"
git status "${1}"
