#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "[g]it [a]dd [file-path]"

[[ "${1}" == "-h" || "${1}" == "--help" ]] && exit 1

if [[ $# -eq 0 ]]; then
  log_message "❯ git add . ':(exclude,glob)**/status' ':(exclude,glob)**/resume'"
  git add . ':(exclude,glob)**/status' ':(exclude,glob)**/resume'
  log_message "❯ git status"
  git status
  exit 0
fi

log_message "❯ git add ${*} ':(exclude,glob)**/status' ':(exclude,glob)**/resume'"
git add "${@}" ':(exclude,glob)**/status' ':(exclude,glob)**/resume'
log_message "❯ git status"
git status
