#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "[g]it [c]ommit --message [message]"

[[ "${#}" -gt 0 ]] && exit 1

log_message "❯ git commit --message \"${1}\""
git commit --message "$1"
