#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "git diff --staged"

[[ "${#}" -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]] && exit 1

if [[ "${#}" -gt 0 ]]; then
    log_subheading "command: git diff --staged ${1}"
    git diff --staged "${1}"
else
    log_subheading "command: git diff --staged"
    git diff --staged
fi
log_line
