#!/usr/bin/env bash

if [[ $# -gt 0 ]]; then
    echo "[g]it [d]iff [s]taged"
    echo "git diff --staged"
    exit 1
fi

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "git diff --staged"
git diff --staged
log_line
