#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "[g]it [f]etch --all --prune"

[[ "${#}" -gt 0 ]] && exit 1

log_message "❯ git fetch --all --prune"
git fetch --all --prune
