#!/usr/bin/env bash

if [[ $# -gt 0 ]]; then
    echo "[g]it [f]etch"
    echo "git fetch --all --prune"
    exit 1
fi

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "git fetch --all --prune"
git fetch --all --prune
log_line
