#!/usr/bin/env bash

if [[ "${#}" -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]]; then
  echo "[g]it [p]ull [o]rigin [branch-name|current]"
  echo "git pull origin \${branch_name}"
  exit 1
fi

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

if [[ $# -gt 0 ]]; then
  branch_name="${1}"
else
  branch_name="$(git branch --show-current 2>/dev/null)"
  if [[ -z "${branch_name}" ]]; then
    log_error "Failed to determine current branch"
    exit 1
  fi
fi

log_title "git pull origin ${branch_name}"
git pull origin "${branch_name}"
log_line
