#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "[g]it [pull] origin [branch-name|current-branch]"

[[ "${#}" -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]] && exit 1

if [[ $# -gt 0 ]]; then
  branch_name="${1}"
else
  branch_name="$(git branch --show-current 2>/dev/null)"
  if [[ -z "${branch_name}" ]]; then
    log_error "Failed to determine current branch"
    exit 1
  fi
fi

log_message "❯ git pull origin ${branch_name}"
git pull origin "${branch_name}"
