#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "sudo [d]ocker [c]ontainer [l]ist"

[[ "${#}" -gt 0 ]] && exit 1

log_subheading "command: sudo docker container list --all"
sudo docker container list --all
log_line
