#!/usr/bin/env bash

title="sudo [d]ocker [c]ontainer [l]ist"
if [[ $# -gt 0 ]]; then
    cat <<EOT
      Title: ${title}
      Usage: dcl [-h]
Description: Displays the list of Docker containers including both running and stopped containers
   Commands:
     - sudo docker container list --all
EOT
    exit 1
fi

echo "${title}"
docker container list --all
