#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "[d]ocker [i]mage [l]ist"

[[ $# -gt 0 ]] && exit 1

log_subheading "command: docker image list"
docker image list
log_line
