#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "[d]ocker [l]ist <multiple-resources>"

[[ $# -gt 0 ]] && exit 1

log_subheading "command: docker container list --all"
docker container list --all

log_subheading "command: docker image list --all"
docker image list --all

log_subheading "command: docker volume list"
docker volume list

log_subheading "command: docker network list"
docker network list

log_line
