#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "sudo [d]ocker [s]top"

[[ $# -gt 0 ]] && exit 1

log_subheading "command: sudo docker stop \$(docker ps -aq)"
if [[ "$(docker ps -aq)" ]]; then
  sudo docker stop "$(docker ps -aq)"
else
  log_message "No containers running"
fi
log_line
