#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "[d]ocker [s]ystem [p]rune [clean]"

[[ $# -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]] && exit 1

if [[ "$1" == "clean" ]]; then
  log_subheading "command: docker stop \$(docker ps -aq)"
  if [[ "$(docker ps -aq)" ]]; then
    docker stop "$(docker ps -aq)"
  else
    log_message "No containers running"
  fi
fi

log_subheading "command: docker system prune --all"
docker system prune --all
log_line
