#!/usr/bin/env bash

usage() {
    echo 'Usage: dsp [clean]'
    echo
    echo 'Runs the "docker system prune --all" command to remove all stopped containers and images'
    echo
    echo 'Optional arguments:'
    echo '  -h, --help             Show this help message and exit'
    echo '  clean                  Stop all running containers before pruning'
}

if [[ $# -gt 1 ]]; then
    usage
    exit 1
fi

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    usage
    exit 0
fi

if [[ "$1" == "clean" ]]; then
    echo "Stopping all running containers..."
    docker stop $(docker ps -aq)
fi

docker system prune --all
