#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "sudo [s]ystemctl [s]tart [d]ocker"

[[ "${#}" -gt 0 ]] && exit 1

log_subheading "command: sudo systemctl start docker"
sudo systemctl start docker

log_subheading "command: sudo systemctl status docker --no-pager"
sudo systemctl status docker --no-pager
log_line
