#!/usr/bin/env bash

# Environment setup
set -o pipefail

# Get the directory of the script file
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
export PATH="${PATH}:${SCRIPT_DIR}"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

function print_usage() {
  cat <<EOF
Usage: $(basename "$0") [-h]

Gets a list of all of the pulic IP addresses over all Projects

Dependencies:
  gcloud             The GCP command line tool

Optional arguments:
  -h, --help         Show this help message and exit
EOF
}

if [[ $# -gt 0 ]]; then
  print_usage
  exit 1
fi

# Dependency check - edit this list adding commands
dependencies=(gcloud)
for cmd in "${dependencies[@]}"; do
    if ! command -v "${cmd}" >/dev/null; then
        log_error "ERROR: Missing dependency - '${cmd}'"
        exit 1
    fi
done

log_title "GCP Pulic IP Addresses"

projects=$(gcloud projects list --format="value(project_id)" | sort | uniq)

for project in ${projects}
do
    if [[ $(gcloud services list --project "${project}" --format="table(NAME)" | sed '1d') =~ "compute.googleapis.com" ]];then
       log_header "${project}"
       gcloud compute addresses list --project "${project}"
       gcloud compute addresses list --project "${project}" --global
    fi
done