#!/usr/bin/env bash

source "$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)/init.sh"

log_tf_title "[t]erraform [a]pply [plan-file]"

[[ "${#}" -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]] && exit 1

if [[ -n "${1}" ]]; then
  log_message "❯ terraform apply ${1}"
  terraform apply "${1}"
  exit 0
fi

log_message "❯ terraform apply"
terraform apply
