#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "[t]erraform [a]pply [aa]"

[[ "${#}" -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]] && exit 1

if [[ "${1}" == "aa" ]]; then
  log_subheading "command: terraform apply -auto-approve"
  terraform apply -auto-approve
  log_line
  exit 0
fi

log_subheading "command: terraform apply"
terraform apply
log_line
