#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "[t]erraform [d]estroy"

[[ "${#}" -gt 0 ]] && exit 1

log_message "❯ terraform destroy"
terraform destroy
