#!/usr/bin/env bash

source "$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)/init.sh"

log_tf_title "[t]erraform [d]estroy"

[[ "${#}" -gt 0 ]] && exit 1

log_message "❯ terraform destroy"
terraform destroy
