#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "[t]erraform [i]nit [bucket-name]"

[[ "${#}" -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]] && exit 1

log_message "Removing .terraform directory and .terraform.lock.hcl file"
log_subheading "rm -rf .terraform && rm -f .terraform.lock.hcl"
rm -rf .terraform && rm -f .terraform.lock.hcl

if [[ -z "${1}" ]]; then
  log_subheading "command: terraform init -upgrade"
  terraform init -upgrade
else
  log_subheading "command: terraform init -upgrade -backend-config=\"bucket=${1}\""
  log_message "Bucket Name: '${1}'"
  terraform init -upgrade -backend-config="bucket=${1}"
fi
log_line
