#!/usr/bin/env bash

source "$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)/init.sh"

log_tf_title "[t]erraform [i]mport <resource> <id>"

[[ $# -ne 2 || "${1}" == "-h" || "${1}" == "--help" ]] && exit 1

log_message "❯ terraform import ${1} ${2}"
terraform import "${1}" "${2}"
