#!/usr/bin/env bash

source "$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)/init.sh"

log_tf_title "[t]erraform [i]nit & [p]lan [target-module]"

[[ "${#}" -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]] && exit 1

MODULE_NAME="${1:-}"

log_message "Removing .terraform directory and .terraform.lock.hcl file"
log_message "❯ rm -rf .terraform && rm -f .terraform.lock.hcl"
rm -rf .terraform && rm -f .terraform.lock.hcl
log_message "❯ terraform init -upgrade"
terraform init -upgrade

"$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)/tp" "${MODULE_NAME}"
