#!/usr/bin/env bash

source "$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)/init.sh"

log_tf_title "[t]erraform [l]int"

[[ "${#}" -gt 0 ]] && exit 1

log_message "Running terraform formatting and linting tools"

log_heading "Formatting"
log_message "❯ terraform fmt -recursive"
terraform fmt -recursive

log_heading "Validating"
log_message "❯ terraform validate"
terraform validate

log_heading "Linting"
log_message "❯ tflint --recursive"
tflint --recursive

log_heading "Security scanning with trivy"
log_message "❯ trivy config ."
trivy config .
