#!/usr/bin/env bash

if [[ "${#}" -gt 0 ]]; then
  echo "[t]erraform [p]lan"
  echo "terraform plan"
  exit 1
fi

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "terraform plan"
terraform plan
log_line
