#!/usr/bin/env bash

source "$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)/init.sh"

log_tf_title "[t]erraform [p]lan"

[[ "${#}" -gt 0 ]] && exit 1

PLAN_FILE="$(new_tf_plan_file)"

log_message "Saving plan to:"
log_message "'${PLAN_FILE}'"
log_message "❯ terraform plan -out='$(basename "${PLAN_FILE}")'"
terraform plan -out="${PLAN_FILE}"
