#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "[t]erraform [p]lan [s]ummary"

[[ "${#}" -gt 0 ]] && exit 1

log_subheading "command: terraform plan | rg '# |Plan:' | rg -v '\.data\.|# \('"
terraform plan | rg '# |Plan:' | rg -v '\.data\.|# \('
log_line
