#!/usr/bin/env bash

usage() {
    cat <<EOF

Usage: ts [-h]

Terraform Show

Runs a Terraform Show

Optional arguments:
  -h, --help             Show this help message and exit

EOF
}

if [[ "${#}" -gt 0 ]]; then
    usage
    exit 0
fi

terraform show
