#!/usr/bin/env bash

usage() {
    cat <<EOF

Usage: tsl [-h]

Terraform State List

Runs a Terraform State List

Optional arguments:
  -h, --help             Show this help message and exit

EOF
}

if [[ "${#}" -gt 0 ]]; then
    usage
    exit 0
fi

terraform state list
