#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "[t]erraform [s]tate [l]ist"

[[ "${#}" -gt 0 ]] && exit 1

log_message "❯ terraform state list"
terraform state list
