#!/usr/bin/env bash

source "$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)/init.sh"

log_tf_title "[t]erraform [s]tate [l]ist"

[[ $# -gt 0 ]] && exit 1

log_message "❯ terraform state list"
terraform state list
