#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "[t]erraform [s]tate [m]o[v]e <source> <dest>"

[[ "${#}" -ne 2 || "${1}" == "-h" || "${1}" == "--help" ]] && exit 1

log_subheading "command: terraform state mv ${1} ${2}"
terraform state mv "${1}" "${2}"
log_line
