#!/usr/bin/env bash

usage() {
    cat <<EOF

Usage: tsmv <source> <dest> [-h]

Terraform State MV

Runs a Terraform State Move

Required arguments:
  source                 Source resource name
  dest                   Destination resource name

Optional arguments:
  -h, --help             Show this help message and exit

EOF
}

if [[ "${#}" -ne 2 ]] || [[ "${1}" == "-h" ]] || [[ "${1}" == "--help" ]]; then
    usage
    exit 0
fi

terraform state mv "${1}" "${2}"
