#!/usr/bin/env bash

source "$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)/init.sh"

log_tf_title "[t]erraform [s]tate [r]e[m]ove <resource-id>"

[[ $# -ne 1 || "${1}" == "-h" || "${1}" == "--help" ]] && exit 1

log_message "❯ terraform state rm ${1}"
terraform state rm "${1}"
