#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "[t]erraform [w]atch"
log_message "This command will run 'terraform fmt -recursive' and 'terraform validate'"
log_message "on every file change in the current directory."

[[ "${#}" -gt 0 ]] && exit 1

log_message "❯ rg -l '.' | entr -c bash -c \"echo \\\"-- \$(date +%T) --\\\" && terraform fmt -recursive && terraform validate\""
log_pressanykey

rg -l '.' | entr -c bash -c "echo \"-- \$(date +%T) --\" && terraform fmt -recursive && terraform validate"
