#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "[g]lab [m]r [v]iew --web"

[[ $# -gt 0 ]] && exit 1

log_message "❯ glab mr view --web"
glab mr view --web
