#!/usr/bin/env bash

if [[ $# -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]]; then
    echo "[k]ubectl [d]escribe [s]tatefulset [a]ll namespaces"
    echo "kubectl describe statefulset --all-namespaces [filter]"
    exit 1
fi


if [[ -z "${1}" ]]; then
    kubectl describe statefulset --all-namespaces
else
    statefulsets="$(kubectl describe statefulset --all-namespaces)"
    echo "${statefulsets}" | head -n 1
    echo "${statefulsets}" | rg "${1}"
fi