#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "[k]ubectl [d]escribe [st]ateful[s]et [statefulset-name]"

[[ "${#}" -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]] && exit 1

if [[ -z "${1}" ]]; then
  log_message "❯ kubectl describe statefulset"
  kubectl describe statefulset
  exit 0
fi

log_message "❯ kubectl describe statefulset ${1}"
kubectl describe statefulset "${1}"
