#!/usr/bin/env bash

if [[ $# -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]]; then
    echo "[k]ubectl [g]et [c]onfigmap"
    echo "kubectl get configmap [configmap-name]"
    exit 1
fi

kubectl get configmap "${1}"
