#!/usr/bin/env bash

if [[ $# -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]]; then
    echo "[k]ubectl [g]et [c]onfigmap output [y]aml"
    echo "kubectl get configmap [configmap-name] --output=yaml"
    exit 1
fi

kubectl get configmap "${1}" --output="yaml"
