#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "[k]ubectl [g]et [c]onfigmap output [y]aml [configmap-name]"

[[ $# -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]] && exit 1

if [[ -z "${1}" ]]; then
  log_message "❯ kubectl get configmap --output=yaml"
  kubectl get configmap --output="yaml"
  exit 0
fi

log_message "❯ kubectl get configmap ${1} --output=yaml"
kubectl get configmap "${1}" --output="yaml"
