#!/usr/bin/env bash

if [[ $# -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]]; then
    echo "[k]ubectl [g]et [d]eployment"
    echo "kubectl get deployment [deployment-name]"
    exit 1
fi

if [[ -z "${1}" ]]; then
    kubectl get deployment
else
    kubectl get deployment "${1}"
fi