#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "[k]ubectl [g]et [d]aemon[s]et output [y]aml [daemonset-name]"

[[ $# -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]] && exit 1

if [[ -z "${1}" ]]; then
  log_message "❯ kubectl get daemonset --output yaml"
  kubectl get daemonset --output="yaml"
  exit 0
fi

log_message "❯ kubectl get daemonset ${1} --output yaml"
kubectl get daemonset "${1}" --output="yaml"
