#!/usr/bin/env bash

if [[ $# -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]]; then
    echo "[k]ubectl [g]et [d]eployment output [y]aml"
    echo "kubectl get deployment [deployment-name] --output=yaml"
    exit 1
fi

source "$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)/_bash_functions"
get_k8s_resource deployment "${1}" yaml
