#!/usr/bin/env bash

if [[ $# -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]]; then
    echo "[k]ubectl [g]et [d]eployment output [y]aml"
    echo "kubectl get deployment [deployment-name] --output=yaml"
    exit 1
fi

kubectl get deployment "${1}" --output="yaml"
