#!/usr/bin/env bash

if [[ $# -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]]; then
    echo "[k]ubectl [g]et [e]ndpoints"
    echo "kubectl get endpoints [endpoint-name]"
    exit 1
fi

if [[ -z "${1}" ]]; then
    kubectl get endpoints
else
    kubectl get endpoints "${1}"
fi