#!/usr/bin/env bash

if [[ $# -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]]; then
    echo "[k]ubectl [g]et [e]ndpoint [a]ll namespaces"
    echo "kubectl get endpoints --all-namespaces [filter]"
    exit 1
fi

if [[ -z "${1}" ]]; then
    kubectl get endpoints --all-namespaces
else
    deployments="$(kubectl get endpoints --all-namespaces)"
    echo "${deployments}" | head -n 1
    echo "${deployments}" | rg "${1}"
fi