#!/usr/bin/env bash

if [[ $# -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]]; then
    echo "[k]ubectl [g]et [e]ndpoints output [y]aml"
    echo "kubectl get endpoints [endpoint-name] --output=yaml"
    exit 1
fi

if [[ -z "${1}" ]]; then
    kubectl get endpoints --output yaml
else
    kubectl get endpoints "${1}" --output yaml
fi