#!/usr/bin/env bash

if [[ $# -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]]; then
    echo "[k]ubectl [g]et [i]ngress"
    echo "kubectl get ingress [ingress-name]"
    exit 1
fi

kubectl get ingress "${1}"
