#!/usr/bin/env bash

if [[ $# -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]]; then
    echo "[k]ubectl [g]et [j]ob output [y]aml"
    echo "kubectl get job [job-name] --output=yaml"
    exit 1
fi

kubectl get job "${1}" --output="yaml"
