#!/usr/bin/env bash

if [[ $# -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]]; then
    echo "[k]ubectl [g]et [n]ame[s]pace output [y]aml"
    echo "kubectl get namespace [namespace-name] --output=yaml"
    exit 1
fi

kubectl get namespace "${1}" --output="yaml"
