#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "[k]ubectl [g]et [n]ode output [y]aml [node-name]"

[[ "${#}" -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]] && exit 1

if [[ -z "${1}" ]]; then
  log_message "❯ kubectl get node --output=yaml"
  kubectl get node --output="yaml"
  exit 0
fi

log_message "❯ kubectl get node ${1} --output=yaml"
kubectl get node "${1}" --output="yaml"
