#!/usr/bin/env bash

if [[ $# -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]]; then
    echo "[k]ubectl [g]et [n]ode output [y]aml"
    echo "kubectl get node [node-name] --output=yaml"
    exit 1
fi

kubectl get node "${1}" --output="yaml"
