#!/usr/bin/env bash

if [[ $# -gt 0 ]]; then
    echo "[k]ubectl [g]et [p]od all namespaces [n]ot [r]unning"
    echo "kubectl get pods --all-namespaces --field-selector=status.phase!=Running"
    exit 1
fi

kubectl get pods --all-namespaces --field-selector=status.phase!=Running
