#!/usr/bin/env bash

if [[ $# -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]]; then
    echo "[k]ubectl [g]et [p]od output [y]aml"
    echo "kubectl get pod [pod-name] --output=yaml"
    exit 1
fi

kubectl get pod "${1}" --output="yaml"
