#!/usr/bin/env bash

if [[ $# -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]]; then
    echo "[k]ubectl [g]et [r]eplica[s]et"
    echo "kubectl get replicaset [replicaset-name]"
    exit 1
fi

kubectl get replicaset "${1}"
