#!/usr/bin/env bash

if [[ $# -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]]; then
    echo "[k]ubectl [g]et [s]ecret"
    echo "kubectl get secret [secret-name]"
    exit 1
fi

kubectl get secret "${1}"
