#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "[k]ubectl [g]et [s]ervice[acc]ount output [y]aml [service-account-name]"

[[ "${#}" -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]] && exit 1

if [[ -z "${1}" ]]; then
  log_message "❯ kubectl get serviceaccount --output=yaml"
  kubectl get serviceaccount --output="yaml"
  exit 0
fi

log_message "❯ kubectl get serviceaccount ${1} --output=yaml"
kubectl get serviceaccount "${1}" --output="yaml"
