#!/usr/bin/env bash

if [[ $# -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]]; then
    echo "[k]ubectl [g]et [s]ervice[acc]ount output [y]aml"
    echo "kubectl get serviceaccount [service-account-name] --output yaml"
    exit 1
fi

source "$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)/_bash_functions"
kubectl get serviceaccount "${1}" --output="yaml"
