#!/usr/bin/env bash

if [[ $# -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]]; then
    echo "[k]ubectl [g]et [s]ervice[acc]ount"
    echo "kubectl get serviceaccount [service-account-name]"
    exit 1
fi

kubectl get serviceaccount "${1}"
