#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "[k]ubectl [g]et [s]ecret [a]ll namespaces"

[[ "${#}" -gt 0 ]] && exit 1

log_message "❯ kubectl get secret --all-namespaces"
kubectl get secret --all-namespaces
