#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "[k]ubectl [g]et [st]ateful[s]et output [y]aml [statefulset-name]"

[[ "${#}" -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]] && exit 1

if [[ -z "${1}" ]]; then
  log_message "❯ kubectl get statefulset --output=yaml"
  kubectl get statefulset --output="yaml"
  exit 0
fi

log_message "❯ kubectl get statefulset ${1} --output=yaml"
kubectl get statefulset "${1}" --output="yaml"
