#!/usr/bin/env bash

if [[ $# -gt 0 ]]; then
    echo "[k]ubectl [g]et [st]ateful[s]et [a]ll namespaces"
    echo "kubectl get statefulset --all-namespaces"
    exit 1
fi

kubectl get statefulset --all-namespaces
