#!/usr/bin/env bash

if [[ $# -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]]; then
    echo "[k]ubectl [g]et [s]ervice"
    echo "kubectl get service [service-name]"
    exit 1
fi

kubectl get service "${1}"
