#!/usr/bin/env bash

if [[ $# -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]]; then
    echo "[k]ubectl [g]et [s]ecret output [y]aml"
    echo "kubectl get secret [secret-name] --output=yaml"
    exit 1
fi

kubectl get secret "${1}" --output="yaml"
