#!/usr/bin/env bash

if [[ $# -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]]; then
    echo "[k]ubectl [g]et persistent [v]olume"
    echo "kubectl get persistentvolume [persistentvolume-name]"
    exit 1
fi

kubectl get persistentvolume "${1}"
