#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "[k]ubectl [g]et persistent [v]olume [persistentvolume-name]"

[[ $# -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]] && exit 1

if [[ -z "${1}" ]]; then
  log_message "❯ kubectl get persistentvolume"
  kubectl get persistentvolume
  exit 0
fi

log_message "❯ kubectl get persistentvolume ${1}"
kubectl get persistentvolume "${1}"
