#!/usr/bin/env bash

if [[ $# -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]]; then
    echo "[k]ubectl [g]et persistent [v]olume output [y]aml"
    echo "kubectl get persistentvolume [persistentvolume-name] --output=yaml"
    exit 1
fi

kubectl get persistentvolume "${1}" --output="yaml"
