#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "[k]ubectl [l]ogs [p]od [pod-name]"

[[ "${#}" -ne 1 || "${1}" == "-h" || "${1}" == "--help" ]] && exit 1

log_message "❯ kubectl logs -f pod/${1}"
kubectl logs -f pod/"${1}"
