#!/usr/bin/env bash

if [[ $# -lt 1 || "${1}" == "-h" || "${1}" == "--help" ]]; then
    echo "[k]ubectl rollout [r]estart [s]tatefulset"
    echo "kubectl rollout restart statefulset/<statefulset-name>"
    exit 1
fi

kubectl rollout restart "statefulset/${1}" && \
  watch kubectl get statefulset && \
  kubectl get

