#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "[k]ubectl [t]op [p]od"

[[ "${#}" -gt 0 ]] && exit 1

log_message "❯ kubectl top pod"
kubectl top pod
