#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "[k]ubectl [t]op [p]od [a]ll namespaces [filter]"

[[ "${#}" -gt 1 || "${1}" == "-h" || "${1}" == "--help" ]] && exit 1

if [[ -z "${1}" ]]; then
  log_message "❯ kubectl top pod --all-namespaces"
  kubectl top pod --all-namespaces
  exit 0
fi

log_message "❯ kubectl top pod --all-namespaces | rg ${1}"
pods="$(kubectl top pod --all-namespaces)"
echo "${pods}" | head -n 1
echo "${pods}" | tail -n +2 | rg "${1}"
