#!/usr/bin/env bash

if [[ $# -gt 0 ]]; then
    echo "[w]atch [k]ubectl [g]et [d]eployment"
    echo "watch kubectl get deployment"
    exit 1
fi

watch kubectl get deployment
kubectl get deployment
