#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "[w]atch [k]ubectl [g]et [n]ode"

[[ "${#}" -gt 0 ]] && exit 1

log_message "❯ watch kubectl get node"
watch kubectl get node
kubectl get node
