#!/usr/bin/env bash

set -o pipefail
SCRIPT_DIR="$(cd "${BASH_SOURCE[0]%/*}" || exit 1; pwd)"
source "${SCRIPT_DIR}/../../bash_modules/terminal.sh"

log_title "[w]atch [k]ubectl [g]et [p]od [n]ot [r]unning"

[[ "${#}" -gt 0 ]] && exit 1

log_message "❯ watch kubectl get pod --all-namespaces --field-selector=status.phase!=Running"
watch kubectl get pod --all-namespaces --field-selector=status.phase!=Running
kubectl get pod --all-namespaces --field-selector=status.phase!=Running
